### ISSUE TITLE
chore: enable dependabot

### ISSUE THREAD

**Issue by x448** [fxamacker/cbor#345]
Enable dependabot features Iin GitHub `Settings->Code Security and Analysis` after adding .github/dependabot.yml

```yaml
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"

```
