### ISSUE TITLE
CI: enable linting option to check variable shadowing

### ISSUE THREAD

**Issue by fxamacker** [fxamacker/cbor#570]
### Suggested Solution

Update .golangci-lint.yml to check variable shadowing.

```yml
linters-settings:
  govet:
    check-shadowing: true
```

### Alternative Solution

Install and run latest `golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow`.

```bash
$ go install golang.org/x/tools/go/analysis/passes/shadow/cmd/shadow@latest
$ go vet -vettool=$(which shadow)
```

This alternative approach is useful when latest `cmd/shadow` is newer than the version used by golangci-lint.
